<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class Category extends Model
{
    use SoftDeletes;

    protected $fillable = ['name', 'status', 'author_id'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        Category::creating(function ($category){
            $category->author_id = Auth::user()->id;
        });

        Category::updating(function ($category){
            $category->author_id = Auth::user()->id;
        });
    }
}
